### ISSUE TITLE
Implement user authentication

### ISSUE THREAD

**Issue by pablocrivella** [MustardSeedNL/Fraternos#6]
### Task

- [x] User sign in
- [x] User sign out
- [x] Confirm account
- [x] Reset password
- [x] Lock account on multiple failed attempts
